sources:
  - Anybody.glyphs
axisOrder:
  - wdth
  - wght
  - slnt
familyName: Anybody
buildOTF: false
buildWebfont: false
stat:
  - name: Width
    tag: wdth
    values:
    - name: UltraCondensed
      value: 50
    - name: Condensed
      value: 75
    - name: Normal
      value: 100
      flags: 2
    - name: Expanded
      value: 125
    - name: ExtraExpanded
      value: 150
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: Black
      value: 900
  - name: Slant
    tag: slnt
    values:
    - name: Default
      value: 0
      linkedValue: -10
      flags: 2
    - name: Italic
      value: -10