    sources:
      - Anybody.glyphs
    axisOrder:
      - slnt
      - wdth
      - wght
    familyName: Anybody
    buildStatic: False
    stat:
      Anybody[slnt,wdth,wght].ttf:
      - name: Slant
        tag: slnt
        values:
        - name: Upright
          value: 0
          flags: 2
      - name: Width
        tag: wdth
        values:
        - name: UltraCondensed
          value: 50
        - name: Condensed
          value: 75
        - name: Normal
          value: 100
          flags: 2
        - name: Expanded
          value: 125
        - name: ExtraExpanded
          value: 150
      - name: Weight
        tag: wght
        values:
        - name: Thin
          value: 100
        - name: ExtraLight
          value: 200
        - name: Light
          value: 300
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Medium
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700
        - name: ExtraBold
          value: 800
        - name: Black
          value: 900
          