sources:
  - Anybody.glyphs
axisOrder:
  - wdth
  - wght
  - ital
familyName: Anybody
buildStatic: False
stat:
  Anybody[ital,wdth,wght].ttf:
      - name: Width
        tag: wdth
        values:
        - name: UltraCondensed
          value: 50
        - name: Condensed
          value: 75
        - name: Normal
          value: 100
          flags: 2
        - name: Expanded
          value: 125
        - name: ExtraExpanded
          value: 150
      - name: Weight
        tag: wght
        values:
        - name: Thin
          value: 100
        - name: ExtraLight
          value: 200
        - name: Light
          value: 300
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Medium
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700
        - name: ExtraBold
          value: 800
        - name: Black
          value: 900
      - name: Italic
        tag: ital
        values:
        - name: Roman
          value: 0
          linkedValue: 1
          flags: 2
        - name: Italic
          value: 1